//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontEndFyp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int Event_Id { get; set; }
        public Nullable<int> Restaurant_Id { get; set; }
        public string Event_Type { get; set; }
        public string Event_Price { get; set; }
        public string Status { get; set; }
        public string Time_In { get; set; }
        public string Time_Out { get; set; }
        public string Event_Image { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
