//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontEndFyp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Payment_Id { get; set; }
        public string Payment_Type { get; set; }
        public Nullable<int> Payment_Paid { get; set; }
        public Nullable<int> Reservation_Id_Fk { get; set; }
        public Nullable<int> Total_Payment { get; set; }
        public Nullable<int> Remaining_Amount { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
