//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontEndFyp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Mails = new HashSet<Mail>();
            this.Messages = new HashSet<Message>();
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int User_Id { get; set; }
        public string User_F_Name { get; set; }
        public string User_CNIC { get; set; }
        public string User_Email { get; set; }
        public string User_Phone_ { get; set; }
        public string User_Address { get; set; }
        public string User_L_Name { get; set; }
    
        public virtual ICollection<Mail> Mails { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
